package com.elec5619.gantt.controllers;

import com.elec5619.gantt.DTO.loginDTO;
import com.elec5619.gantt.DTO.registerDTO;
import com.elec5619.gantt.services.AuthService;
import com.elec5619.gantt.tables.user.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

@RestController // This means that this class is a RestController
// Allen (16/10/23) - removed the demo mapping because it was messing with
// accessing the endpoints
public class AuthController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AuthService authService = new AuthService();

    @PostMapping(path = "/add") // Map ONLY POST Requests
    @CrossOrigin(origins = { "http://localhost:5173", "http://localhost:8080" })
    public @ResponseBody void addNewUser(@RequestBody registerDTO newUserDetails) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        authService.signUpHandler(newUserDetails);
    }

    @PostMapping(path = "/login")
    @CrossOrigin(origins = { "http://localhost:5173", "http://localhost:8080" })
    public @ResponseBody Integer userLogIn(@RequestBody loginDTO loginDetails) {
        Integer found = authService.loginHandler(loginDetails).getId();

        if (found != null) {
            return found;
        } else {return null;}
    }

    @GetMapping(path = "/users/all")
    @CrossOrigin(origins = { "http://localhost:5173", "http://localhost:8080" })
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return authService.getAllUsers();
    }

    @GetMapping(path = "/getSpecific")
    @CrossOrigin(origins = { "http://localhost:5173", "http://localhost:8080" })
    public @ResponseBody String getSpecificUser(@RequestBody loginDTO loginDetails) {
        String found = authService.getSpecificUser(loginDetails).getName();

        if (found != null) {
            return found;
        }

        return null;
    }
}
